namespace Drawmasters
{
    public enum ScreenType
    {
        None                    = 0,
        MainMenu                = 1,
        Ingame                  = 2,
        Result                  = 3,

        Settings                = 5,
        Tutorial                = 6,
        ShooterSkinScreen       = 8,
        OkayScreen              = 9,
        RateUsScreen            = 10,
        Roulette                = 11,
        ShopResult              = 12,
        PauseScreen             = 13,
        WeaponSkinScreen        = 14,
        LoadingScreen           = 15,
        RateUsFeedbackScreen    = 16,
        SubscriptionScreenRoot  = 17,
        SubscriptionRewardRoot  = 18,
        SpinRoulette            = 19,
        SpinReward              = 20,
        ForceMeter              = 21,
        BirdHunt                = 22,
        BonusLevelPropose       = 23,
        ShopMenu                = 24,
        Mansion                 = 25,
        CurrencyPropose         = 26,
        PremiumShopResult       = 27,
        MansionMenu             = 28,
        TutorialFinger          = 29,
        Monopoly                = 30,
        HitmastersPreview       = 31,
        HitmastersMap           = 32,
        SeasonPassScreen        = 33,
        SeasonEventScreen       = 34,
        SeasonEventPreview      = 35,
        PetSkinScreen           = 36,
        LeaguePreview           = 37,
        LeagueApply             = 38,
        LeagueLeaderBoard       = 39,
        LeagueChange            = 40,
        MultipleReward          = 41,
        SeasonEventInfo         = 42,
        LeagueInfo              = 43,
        OutfitsSkinScreen       = 44,
        LeagueEnd               = 45,
        CongratulationScreen    = 46,
        NoInternet              = 47,
        PetsChargeTutorial      = 48,
    }
}
